name: BlankOn Live Build

on:
  push:
    branches: [actions]

jobs:
  build:
    name: Build ISO
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup environments
        run: |
          sudo apt update
          sudo apt install -y debootstrap make git
          git clone https://salsa.debian.org/live-team/live-build.git debian-live-build
          cd debian-live-build
          git checkout 7360d50fa6b
          sudo make install
          sudo lb --version
      - name: Install BlankOn keyring
        run: sudo dpkg -i config/packages/blankon-keyring_2020.10.29-1.0_all.deb
      - name: Setup live build
        run: sudo curl https://gist.githubusercontent.com/kudaliar032/df3e7dc22572678bdd322d3b26d4c354/raw/664e1debe496c3f4197169230bcc5c65807bf69b/verbeek -o /usr/share/debootstrap/scripts/verbeek
      - name: Kick build 
        run: bash build.sh
