name: BlankOn Live Build

on:
  push:
    branches: [actions]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup environments
        run: |
          sudo apt update
          sudo apt install -y debootstrap make git
          git clone https://salsa.debian.org/live-team/live-build.git debian-live-build
          cd debian-live-build
          git checkout 7360d50fa6b
          sudo make install
          sudo lb --version
      - name: Install BlankOn keyring
        run: sudo dpkg -i config/packages/blankon-keyring_2020.10.29-1.0_all.deb
      - name: Setup live build
        run: |
          sudo su -
          cat <<EOF > /usr/share/debootstrap/scripts/verbeek
          mirror_style release
          download_style apt
          finddebs_style from-indices
          variants - buildd fakechroot minbase
          keyring /usr/share/keyrings/blankon-archive-keyring.gpg

          # include common settings
          if [ -e "$DEBOOTSTRAP_DIR/scripts/debian-common" ]; then
            . "$DEBOOTSTRAP_DIR/scripts/debian-common"
          elif [ -e /debootstrap/debian-common ]; then
            . /debootstrap/debian-common
          elif [ -e "$DEBOOTSTRAP_DIR/debian-common" ]; then
            . "$DEBOOTSTRAP_DIR/debian-common"
          else
            error 1 NOCOMMON "File not found: debian-common"
          fi
          EOF
      - name: Start build
        run: bash build.sh
